### ISSUE TITLE
What is the point of this Repo?

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/Number-Generator-#1]
What is this going to be used for?

**Comment by jiang11** [comment]
That's the question. It's just a number generator

**Comment by jasonwynn10** [comment]
0 sense with that answer...

**Comment by jiang11** [comment]
A fun number generator :/

**Comment by jiang11** [comment]
Like, raffle tickets?

**Comment by jasonwynn10** [comment]
eh... whats a more practical purpose? there are already a million on the Internet

**Comment by jiang11** [comment]
😕I mean if it's not good you can always delete it.

**Comment by MCUnderground** [comment]
No deleting... Maybe add some fetures? :)
